# Generated by Django 4.2.6 on 2023-10-22 21:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_used_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statuschange',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 22, 21, 43, 30, 391211, tzinfo=datetime.timezone.utc)),
        ),
    ]
