# Generated by Django 4.2.6 on 2023-10-26 14:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_role_userdepartment_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statuschange',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 26, 14, 57, 56, 501724, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='used',
            name='given_amount',
            field=models.CharField(max_length=50),
        ),
    ]
