# Generated by Django 4.2.5 on 2023-10-28 11:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_statuschange_date_alter_used_given_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statuschange',
            options={'ordering': ('-date', 'efs__code')},
        ),
        migrations.RenameField(
            model_name='message',
            old_name='msg',
            new_name='message',
        ),
        migrations.AlterField(
            model_name='statuschange',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 28, 11, 11, 46, 349159, tzinfo=datetime.timezone.utc)),
        ),
    ]
