# Generated by Django 4.2.5 on 2023-11-01 04:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_statuschange_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statuschange',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 1, 4, 16, 48, 759162, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='used',
            name='given_amount',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
