# Generated by Django 4.2.7 on 2023-11-03 21:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_statuschange_date_alter_used_given_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='efs',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 3, 21, 13, 35, 307540, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='statuschange',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 3, 21, 13, 35, 308573, tzinfo=datetime.timezone.utc)),
        ),
    ]
