# Generated by Django 4.2.7 on 2023-11-05 11:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_efs_date_alter_statuschange_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='efs',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 5, 11, 26, 7, 187429, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='statuschange',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 5, 11, 26, 7, 188447, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='statuschange',
            name='new_status',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='statuschange',
            name='old_status',
            field=models.CharField(max_length=50),
        ),
    ]
